### PR TITLE
Add some UI customization

### PR DESCRIPTION
**Pull request by DominicWindisch**
I've added some basic options to change primary/secondary color and the button labels (at least the ones exposed to non-admins). 

I guess the UI-Settings should be refactored at one point (UI vs Theme?) but I didn't want to overhaul too much at once.. 😬 

Related to https://github.com/photobooth-app/photobooth-app/pull/165.

### CODE REVIEW

**Comment by mgineer85** [comment]
Hi, thx for the pull request :)

I will check it later.

The UI is just grown and has no architecture behind it yet 😔 So there is room for improvement for sure.
I thought to add language translation at one point - that would be a way to customize texts also. But I am not yet there.
For now this solution seems convenient.

Which linter/formatter do you use? It seems its reformatted and I do not have a good one yet configured in the frontend.

**Comment by DominicWindisch** [comment]
Hi, 

yeah I've seen the translation issue - a bit too late though 😅 Certainly the way to move forward.

I've just setup everything from scratch on a windows machine (python, npm, vs code, quasar, ...). I've got quite some experience in a (conceptually similar) vanilla js/html/css/PHP project but I haven't done anything yet using vue. So I just ran with the defaults as it's described in the readme (`yarn lint`, `yarn format`). For some reason, config page was reformatted quite a bit already in vs code 🙈

**Comment by DominicWindisch** [comment]
Hello again ✌️ 

I've added translations to the Frontend using i18n (as suggested in https://github.com/photobooth-app/photobooth-app/issues/86).

Two issues remain as of now:
- The selected language is not persistent, i.e. it defaults back to English when reloading the page. Is there some kind of persistent storage allready in place for the frontend? Else I'd likely just store it using something along the lines of `localStorage.setItem('locale')`.
- I was not yet able to translate the messages in some of the notifactions (e.g. [here](https://github.com/DominicWindisch/photobooth-frontend/blob/add-ui-customization/src/pages/ConfigPage.vue#L277)). Likely something obvious for someone more experieneced in Vue.

**Comment by DominicWindisch** [comment]
I'm "done" with the UI adaptations for now (meaning my wife is happy with the result). Let me just quickly summarize them so you can at least try to make sense of this PR (files not mentioned here are just reformated for some reason):

- README.md: Just documented my struggles with getting the local server to run on Windows.
- package.json: Added vue-i18n for translations.
- quasar.config.js: Added vue-i18n for translations.
- src/boot/blitzar.js: Add "ColorPicker" component for theming.
- src/boot/i18n.js: Initializes translations from browser storage.
- src/components/ColorPicker: ColorPicker component with input validation on color strings and a popup, well, color picker.
- src/components/ConnectionOverlay: add translations
- src/components/CountdownTimer: 
  - made larger, 
  - countdown shows only integer value (the decimal place was cutoff and it jumped between, e.g. "2.1", "2", "1.9", etc). 
  - Uses primary/secondary color now.
  - Icon before capture was replaced by a div (so one can use "Smile!" for example)
- src/components/GalleryImageDetail
  - users are now always allowed to delete in `singleItemView` mode (i.e. to delete their own captured image)
  - before deleting, a confirmation popup is displayed
  - added translations
- src/components/LanguageSwitcher: drop down menu to select locale (somewhat oddly placed for mobile UI, couldn't think of a better place, tho)
- src/i18n/de-DE/index.js: German translation of app strings
- src/i18n/en-US/index.js: English (default) translation of app strings
- src/i18n/index.js: list of translated languages
- src/layouts/AdminLayout: added translations and language switcher
- src/layouts/GalleryLayout: added translations
- src/pages/AdminFilesPage: added translations
- src/pages/AdminPage: added translations
- src/pages/ConfigPage: added translations
- src/pages/ErrorNotFound: added translations
- src/pages/IndexPage: 
  - added translations
  - add specific gallery buttons styling (so I can move it around more fittingly to my overlay image on the frontpage)
  - display "processing" animation also in "capture" state instead of a blank page while the camera does its thing
- src/pages/ItemApprovalPage: added translations
- src/stores/ui-settings-store: apply theme colors on initStore

**Comment by DominicWindisch** [comment]
Nitpicker here: the galleryimagedetail component is not used (although included) in itemapprovalpage - so there's no way to delete mid-process. :)

**Comment by mgineer85** [comment]
> Nitpicker here: the galleryimagedetail component is not used (although included) in itemapprovalpage - so there's no way to delete mid-process. :)

holy, you're right. reverted my commit :)

**Comment by mgineer85** [comment]
merged! thank you very much for all these additions :)

**Comment by mgineer85** [comment]
Released a new v2 alpha2 with all latest improvements: https://github.com/photobooth-app/photobooth-app/releases/tag/v2.0a2

Thx! 🎉

**Pull request merged**
