### PR TITLE
Config multiple collages

### PR DESCRIPTION
**Pull request by DominicWindisch**
This PR adds the necessary frontend changes to allow users to configure and start a variable number of collages and/or animations.

__To be merged after slideshow.__ 25/26 commits are from there  😬 

Summary:
- ConfigPage: 
  - Differentiate between "normal" settings and groups thereof. 
  - Use title property of the setting in the side bar (looks nicer :) )
- IndexPage: 
  - Iterate over all configured animation/collage pipelines and show a button for each one for which "display_on_frontend" is true
  - Clicking the respective button will transmit its index to the backend for proper processing
  - User can define the button string. If empty, it'll be the translated value of plus the index, i.e. "Collage-1", "Collage-2",... 
- router:
  - add route for config/?section/?subsection to access child elements
- ui-settings-store:
  - will now hold the complete app configuration. From a UX standpoinnt, it just made more sense to have the "show on frontend" and "configuration name" properties in the respective mediaprocessing_pipeline_collage. So we also have to download the mediaprocess_pipelines_collage and mediaprocessing_pipelines_animation props... i.e. we may aswell load them all :)

### CODE REVIEW

**Comment by mgineer85** [comment]
With all latest PR merged in a test branch it seems there is an issue with initialization the ui:
image

**Comment by mgineer85** [comment]
To trigger jobs there are 3 ways currently:
- touchscreen (rest api/http)
- GPIO
- keyboard
How would GPIO/keyboard trigger which definition of collage?

Maybe we can let BlitzForms handle the addition of multiple definitions transparently without need to add set the number of collages/animations somewhere else?

**Comment by DominicWindisch** [comment]
Do you overwrite the config in your setup (config.json or environment)? THe prop istself is [included in the commit](https://github.com/DominicWindisch/photobooth-app/blob/a2dbda7af074463e5c3deb681e41308294040c05/photobooth/services/config/groups/mediaprocessing.py#L218). Seems like the pipeline list of configs is not found, hence the display_on_frontpage prop can't be accessed.

I've setup a "complete" branch myself [here](https://github.com/DominicWindisch/photobooth-app/tree/deploy_local), which works fine on my raspi.

> Maybe we can let BlitzForms handle the addition of multiple definitions transparently without need to add set the number of collages/animations somewhere else?

I'd just add an option in the GPIO/keyboard settings as to which config should be triggered. I can't really see any other way of transparently adding them. But I'm not an expert of any of the involved frameworks, it was quite a hassle for me to even get this one going. 🥲

**Comment by DominicWindisch** [comment]
Just double checked; it's working locally with virtual cam; it's not working with gphoto2. I can have a deeper look tomorrow.

**Comment by DominicWindisch** [comment]
There was a file missing from the commit. Still behaving weirdly with gphoto2 sometimes...

**Comment by DominicWindisch** [comment]
Screenshot_20240216-223902

I've got some pretty weird behavior on the RPI instance. The processing state machine instantly terminates the job after transition to asking the user for approval, even though it prints that it should wait for approval and the number of captures is also correct. It works perfectly fine in automatic mode. Any idea what could be wrong there? Didn't touch the state machine and I'm out of ideas 😔

**Comment by mgineer85** [comment]
I check that, this one could be a bug introduced earlier by me when revising the statemachine.

**Comment by mgineer85** [comment]
Updated to latest PR's but still having issues:

image

**Comment by DominicWindisch** [comment]
Cleaned up the PR and updated frontend in photobooth-App PR. I just installed that PR on a raspi and it's working fine (except the state machine issue).

If your still missing the display_on_frontpage thing, could you please post the config scheme returned from the backend?

I'll have a look at the state machine issue later today and finish this PR once that's ironed out.

**Comment by mgineer85** [comment]
Since removing blitzar is on the list anyway, before continue with this feature I propose to finish implementation of jsonforms in the frontend.
It consumes jsonschema similar to the schema pydantic produces and allows to create nested layouts to define for example an array of collages.

https://github.com/photobooth-app/photobooth-frontend/issues/11

Once this is implemented, the config for collages are easy and just a backend-topic then ;)

No timeline when #11 is finished yet unfortunately.

**Comment by DominicWindisch** [comment]
Sounds good to me. 👍

**Comment by mgineer85** [comment]
A different approach using unlimited actions per mode (single image, collage, animation or video) is implemented in upcoming v3. 
Alpha is released.

**Pull request closed without merging**
